name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_nav_bar: ^2.0.1
  google_maps_flutter: ^0.4.0
  countdown_flutter: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/a.png
    - images/a1.png
    - images/a10.png
    - images/a11.png
    - images/a12.png
    - images/a13.png
    - images/a14.png
    - images/a15.png
    - images/a16.png
    - images/a17.png
    - images/a19.png
    - images/a2.png
    - images/a20.png
    - images/a21.png
    - images/a22.png
    - images/a23.png
    - images/a24.png
    - images/a25.png
    - images/a26.png
    - images/a27.png
    - images/a28.png
    - images/a29.png
    - images/a3.png
    - images/a30.png
    - images/a31.png
    - images/a32.png
    - images/a33.png
    - images/a34.png
    - images/a35.png
    - images/a36.png
    - images/a37.png
    - images/a38.png
    - images/a39.png
    - images/a4.png
    - images/a40.png
    - images/a41.png
    - images/a42.png
    - images/a43.png
    - images/a44.png
    - images/a45.png
    - images/a46.png
    - images/a47.png
    - images/a48.png
    - images/a49.png
    - images/a5.png
    - images/a50.png
    - images/a51.png
    - images/a52.png
    - images/a53.png
    - images/a54.png
    - images/a55.png
    - images/a56.png
    - images/a57.png
    - images/a58.png
    - images/a6.png
    - images/a7.png
    - images/a8.png
    - images/a9.png
    - images/acheivement.png
    - images/backgroundimg.png
    - images/bgimg.png
    - images/challenges.png
    - images/challengesscreen.png
    - images/cities.png
    - images/cli.png
    - images/Earth.png
    - images/homebar.png
    - images/homebg.png
    - images/monster.png
    - images/start.png
    - images/timescreen.png
    - images/watersave.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
